W7D5/debug_version/skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :links do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
end

W7D5/debug_version/skeleton/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D5/debug_version/skeleton/app/models/comment.rb
class Comment < ApplicationRecord
  validate :body, presence: true

  belongs_to :user
  has_one :link
end

W7D5/debug_version/skeleton/app/models/link.rb
class Link < ApplicationRecord
  validates :title, :url, presence: true

  belongs_to :user,
    class_name: 'user',
    foreign_key: :user_id,
    primary_key: :id

  has_many :comments,
    class_name: 'Comment',
    primary_key: :link_id,
    foreign_key: :id
end

W7D5/debug_version/skeleton/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6 }

  has_many :links
  has_many :comments

  after_initialize :reset_token!

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.new(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
  end

  private
  def ensure_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
  end
end

W7D5/debug_version/skeleton/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :signed_in?

  private
  def current_user
    @current_user = User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    current_user = user
    session[:session_token] = user.reset_token
  end

  def sign_out
    current_user.try(:reset_token!)
  end

  def require_signed_in!
    redirect_to session_url if signed_in?
  end
end

W7D5/debug_version/skeleton/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_signed_in!

  def create
    comment = Comment.new(comment_params)
    comment.user_id = @current_user.id
    comment.link_id = params[:id]
    comment.save
    flash[:errors] = comment.errors.full_messages
    redirect_to link_url(comment)
  end

  def destroy
    comment = Comment.find(params[:comment_id])
    comment.destroy
    redirect_to link_url(comment.link_id)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

W7D5/debug_version/skeleton/app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_signed_in!

  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    link = Link.new
  end

  def create
    @link = Link.new(params)
    @link.user_id = current_user.id
    if @link.save
      redirect_to links_url(@link)
    else
      flash.now[:errors] = @link.errors
      redirect_to new_link_url
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = current_user.links.find(params[:id])
    if @link.save(link_params)
      redirect_to link_url(@link)
    else
      flash.now[:error] = @link.errors.full_messages.first
      render :edit
    end
  end

  def destroy
    link = Link.find(params[:id])
    link.destroy
    redirect_to link_url(link)
  end

  private
  def link_params
    params.require(:link).permit(:title, :url)
  end
end

W7D5/debug_version/skeleton/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:username],
      params[:password]
    )

    if user.nil?
      sign_in(user)
      redirect_to links_url
    else
      flash.now[:errors] = 'Invalid username or password'
      render :create
    end
  end

  def destroy
    redirect_to new_session_url
  end
end

W7D5/debug_version/skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if user.save
      sign_in
      redirect_to links_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.permit(:user).require(:password, :username)
  end
end

W7D5/debug_version/skeleton/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

W7D5/debug_version/skeleton/app/helpers/comments_helper.rb
module CommentsHelper
end

W7D5/debug_version/skeleton/app/helpers/links_helper.rb
module LinksHelper
end

W7D5/debug_version/skeleton/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D5/debug_version/skeleton/app/helpers/users_helper.rb
module UsersHelper
end

W7D5/debug_version/skeleton/app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

W7D5/debug_version/skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      <%= current_user.username %>
      <%= button_to 'Sign Out', session_url, method: :delete %>
    <% else %>
      <%= link_to 'Sign In', new_session_url %>
      <%= link_to 'Sign Up', new_user_url %>
    <% end %>

    <br>

    <%= render 'layouts/errors' %>

    <%= yield %>
  </body>
</html>

W7D5/debug_version/skeleton/app/views/links/edit.html.erb
<h2>Edit Link</h2>

<form action="<%= link_url(@link) %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="patch">

  <label>
    Title
    <input type="text" name="link[title]" value="<%= @link.title %>">
  </label>

  <label>
    URL
    <input type="text" name="link[url]" value="<%= @link.url %>">
  </label>

  <input type="submit" value="Update Link">
</form>

W7D5/debug_version/skeleton/app/views/links/index.html.erb
<h1>Links</h1>

<ul>
  <% @links.each do |link|%>
    <li><%= link_to link.title, link_url(link) %> : <%= link.url %></li>
  <% end %>
</ul>

<%= link_to 'New Link', new_link_url %>

W7D5/debug_version/skeleton/app/views/links/new.html.erb
<h2>New Link</h2>

<form action="<%= links_url %>" method="post">
  <%= auth_token_input %>

  <label>
    Title
    <input type="text" name="link[title]" value="<%= @link.title %>" id="title">
  </label>

  <label>
    URL
    <input type="text" name="link[url]" value="<%= @link.url %>" id="url">
  </label>

  <input type="submit" value="Create New Link">
</form>

W7D5/debug_version/skeleton/app/views/links/show.html.erb
<h2><%= @link.title %></h2>
By: <%= @link.user.username %>

<%= link_to @link.url, @link.url %>

<h3>Comments</h3>
<ul>
  <% @link.comments.each do |comment| %>
    <li>
      <%= comment.body %>
      <%= button_to 'Remove Comment', comment_url(comment), method: :delete %>
    </li>
  <% end %>
</ul>

<hr>

<h3>Add Comment</h3>

<form action="<%= comments_url %>" method="post">
  <%= auth_token_input %>

  <label>
    Comment
    <input type="text" name="comment[body]" value="">
  </label>

  <input type="submit" value="Add Comment">
</form>

<%= link_to 'Edit Link', edit_link_url(@link) %>
<%= link_to 'Links', links_url %>