W5D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/bands')

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:show, :new, :create] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy,]

  resources :notes, only: [:create, :destroy]
end

W5D1/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
end

W5D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  
  def band_params
    params.require(:band).permit(:name)
  end
end

W5D1/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/music_app/app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form class='form' action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='band-name'>Name</label>
    <input id='band-name' type="text" name="band[name]" value="<%= band.name %>">
  </p>

  <input type="submit">
</form>

W5D1/music_app/app/views/bands/edit.html.erb
<h1 class='page-header'>Edit <%= @band.name %></h1>

<%= render "form", band: @band %>

W5D1/music_app/app/views/bands/index.html.erb
<h1 class='page-header'>Bands</h1>

<ul class='main-list'>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><p><%= band.name %></p></a></li>
  <% end %>
</ul>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_url %>" >New band</a></li>
</ul>

W5D1/music_app/app/views/bands/new.html.erb
<h1 class='page-header'>New Band!</h1>

<%= render "form", band: @band %>

W5D1/music_app/app/views/bands/show.html.erb
<h1 class='page-header'><%= @band.name %></h1>

<h4 class='sub-header'>Albums</h4>

<% if @band.albums.length > 0 %>
  <ul class='main-list'>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><p><%= album.name %></p></a></li>
  <% end %>
  </ul>
<% else %>
  <p>This band has no albums... yet!</p>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_album_url(@band) %>">New album</a></li>
  <li><a class='button' href="<%= edit_band_url(@band) %>">Edit Band</a></li>
  <li>
    <form action="<%= band_url(@band) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Band">
    </form>
  </li>
  <li><a class='button' href="<%= bands_url %>">All bands</a></li>
</ul>